### ISSUE TITLE
Is USB-C connected to ESP32-S3 USB OTG?

### ISSUE THREAD

**Issue by drudru** [Xinyuan-LilyGO/T-Embed#1]
Hi,

I could not find any information about this on your sites.

Is the ESP32-S3 USB OTG connected to the USB-C connector?

**Comment by LilyGO** [comment]
Yes it can. In some older implementations, USB-C may cause the motherboard to not supply power due to a flaw in the design. It has been gradually fixed in the new design.

**Comment by morganrallen** [comment]
@LilyGO are there any board markings to indicate the version?
