### ISSUE TITLE
Can we get a separate user_select file for T_embed in tft_eSPI

### ISSUE THREAD

**Issue by 0x786d** [Xinyuan-LilyGO/T-Embed#12]
In latest TFT_eSPI library by Bodmer, we got setup206 file for T-Display-S3 and if i am not wrong, i guess @mmMicky contributed on it too.  Nevertheless it works great for T-Display-S3 board now.  Can we get a separate file for lilygo T-Embed also?  This would solve big problem for users who are using both boards.   I have tried tft_eSPI library included in this repository and have tried everything what i could do but display of my T-Embed is not working.  I was able to run some sketches from Volos Projects on it before but not anymore even if with current repository's tft_eSPI library.

**Comment by lewisxhe** [comment]
PR has been added to the main branch.
https://github.com/Bodmer/TFT_eSPI/pull/2510
