### ISSUE TITLE
Is there an Arduino format .ino file for the factory code on the T-Embed?

### ISSUE THREAD

**Issue by reflectingme** [Xinyuan-LilyGO/T-Embed#13]
Apologies if I have missed this, but is there an Arduino format file - .ino - (not platformIO) for the factory demo code on the T_Embed please?

**Comment by lewisxhe** [comment]
"All examples should be available. If you encounter any problems that cannot be compiled, please let me know. I will close the problem first, and if there are still problems, please reopen it."

**Comment by reflectingme** [comment]
Thanks @lewisxhe - I checked again and there is still no factory .ino for the T-Embed device in the GitHub repo.  Users can only restore the factory image if they use PlatfomIO, and many don't.

**Comment by lewisxhe** [comment]
Completed, please repurchase
