### ISSUE TITLE
SD dont work.

### ISSUE THREAD

**Issue by onimahoni** [Xinyuan-LilyGO/T-Embed#14]
Hello, 
i compiled the factory example. Everything works except for the sd card.
I tested 3 SD with fat32.  I tested with PlatfromIO and Arduino IDE. 
What am I doing wrong. any solution?

**Comment by lewisxhe** [comment]
I have uploaded the factory test program, please test it. If there are still problems, it may be a hardware problem. I will close the problem first, and if there are still problems, please reopen it.
