### ISSUE TITLE
unable to compile firmware

### ISSUE THREAD

**Issue by m0horus** [Xinyuan-LilyGO/T-Embed#15]
using all recommended methods the firmware file will not compile. 
 Make Error: Unable to (re)create the private pkgRedirects directory:
please provide a working .bin file for the factory image or a .ino file.

**Comment by lewisxhe** [comment]
Firmware has been added, please check

https://github.com/Xinyuan-LilyGO/T-Embed/tree/main/firmware

**Comment by lewisxhe** [comment]
If you encounter any issues that cannot be compiled, please let me know. I will close the issue first, and if there are still issues, please reopen it
