### ISSUE TITLE
Is there a 'boot' button on the T-Embed board as I need to reset

### ISSUE THREAD

**Issue by reflectingme** [Xinyuan-LilyGO/T-Embed#16]
On the t-display and t-display touch boards there is a boot GPIO-0 button that can be used to reset the board in the event of a fail, by holding the boot button down before plugging the USB cable in, then attach the Usb cable, then release and upload the code etc.  This procedure is described in the **TIPS** section of the relevant GitHub pages.

How does one do this on the T-Embed board please?  Mine is currently u/s, I can't use it at all and I cannot get **any** sketch to upload!

Thanks

**Comment by Maestro8484** [comment]
i would like to know this as well.  how does one activate this 'boot' function AND how do you turn the device off when on battery power?

**Comment by reflectingme** [comment]
So, I have discovered the BOOT button GPIO 0 is actually the centre button for the rotary encoder dial.  However, using the same process as described on the T-Display GitHub board page to reset the board via BOOT mode does not work with the T-Embed board.
Frustrating.

**Comment by lesept777** [comment]
It seems possible to reset the T-Embed. GPIO 0 is connected to the encoder button.
Push the encoder button, push the reset button, power on the device, release the reset button then release the encoder button
