### ISSUE TITLE
Colour rendering backgrounds, text or drawn objects with LilyGo supplied TFT_eSPI library is not correct

### ISSUE THREAD

**Issue by reflectingme** [Xinyuan-LilyGO/T-Embed#17]
OK, I have a strange issue and am wondering if anyone can point me in the right direction please.

I am using the LilyGo T-Embed ESP32S3 device which is working _almost_ as I wish, however when using the supplied TFT_eSPI library (the version of which which LilyGo advise MUST be used), the colors displayed and rendered either as backgrounds, text or drawn objects are all incorrect.

For example, the code:

`tft.fillScreen(TFT_RED);`

actually fills the screen with blue!! and this code...

```
tft.setTextColor(TFT_YELLOW, TFT_BLACK);
tft.drawString("testing yellow", 10, 100, 4);
```

... renders teal coloured text and NOT yellow!!

Now, as both the T-Display and Touch versions each use RGB565 for colours which render fine, does the T-Embed board use a different colour format?

![IMG_0948](https://user-images.githubusercontent.com/47534300/223445509-8d0464ef-ff2c-4f8b-8178-bce8a34b4767.png)

**Comment by lewisxhe** [comment]
Fixed, please update the TFT in the lib directory again_ ESPI Library
