### ISSUE TITLE
User_Setup_Select.h contents for T-Embed show selected device at a resolution of 240*240

### ISSUE THREAD

**Issue by reflectingme** [Xinyuan-LilyGO/T-Embed#18]
I own three LilyGo boards, a T-Display, a T-Display Touch and a T-Embed and I am having trouble using the TFT_eSPI library when switching to the T-Embed device.

In the User_Setup_Select.h file which is I believe, the file responsible for determining the correct device configuration for the attached board.  The one selected in this file in the Xinyuan-LilyGo/T-Embed git hub respiratory is line 52;

`#include <User_Setups/Setup24_ST7789.h>            // Setup file for DSTIKE/ESP32/ESP8266 configured for ST7789 240 x 240
`
However, the description in the file refers to a display resolution of 240*240, which of course is not correct for the T-Embed board as this has a resolution of 320 x 170.

So this leads me to ask is this the correct configuration file for this device, can you confirm please and explain why the description resolution states 240 x 240.

ta

**Comment by lewisxhe** [comment]
Updated<TFT_ ESPI>Library. and submit the configuration file to the main branch. Thank you for your support
https://github.com/Bodmer/TFT_eSPI/pull/2510
