### ISSUE TITLE
please add firmware folder

### ISSUE THREAD

**Issue by 369Martin369** [Xinyuan-LilyGO/T-Embed#19]
my T-Embed does not show any display activitiy. So I need to set it to shipping firmware.bin state, in order to check if there is a display hardware failure. I' dont know what I'm doing wrongly  (have correct SPi lib installed) but the display remains black.
Original firmware is only chance to check if system is okay.

Thanks for extending the branch with firmware.bin.
regards, Martin

PS. T-Display 3 and T-HMI work both great, but I failed with T-embed so far.

**Comment by lewisxhe** [comment]
Has been added and the TFT has been updated_ ESPI library. I have completed T-Embed. Thank you for your support
