### ISSUE TITLE
GPIO Pinout reference does not match physical board

### ISSUE THREAD

**Issue by cydergoth** [Xinyuan-LilyGO/T-Embed#21]
On the physical board the GPIO is an 8 pin DIL 0.1" connector, however the GPIO reference diagram shows an 11 pin?! 

Please clarify the correct pinout for this connector.

**Comment by lewisxhe** [comment]
You can see the correct pin definition here in the picture.
The pin diagram is that the later board leads the SPI of the screen to the socket

![image](https://user-images.githubusercontent.com/22990954/230807880-7059db14-0395-4645-9a79-0672875bfd4a.png)
