### ISSUE TITLE
WiFiClientSecure.h and  DNS Failed 

### ISSUE THREAD

**Issue by jalmince** [Xinyuan-LilyGO/T-Embed#24]
Hi Lewis, ( or any knowledgeable guy ... )
Ive been trying to send hhtp request to web services for ages, with no success...
The issue boils down to the following 
doing

#include <Arduino.h>
#include <WiFi.h>
#include <WiFiClientSecure.h>
void try_connect() {
WiFiClientSecure httpClient;
  if (!httpClient.connect("https://www.google.com", 8443)) {
    Serial.println("Connection failed");
    return;
  }_

I systematically get " hostByName(): DNS Failed for https://www.google.com"

what's going on ??
any help appreciated a lot
Thank,
JeanPaul

I am using VsCode/platformIO,
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-s3-devkitc-1.html
PACKAGES:
 - framework-arduinoespressif32 @ 3.20007.0 (2.0.7)

PS if doing WiFiClient ( not the "secure one "), and http ( not "s" ) to www.google 8080 I get the same error.
of course nothing is wrong with my network or router , since I cam connect with my PC!

**Comment by lewisxhe** [comment]
Port 8443? Are you sure there's no problem? The normal encryption port is 443

**Comment by jalmince** [comment]
Thanks Lewis for your reply !

Actually I cant manage to send a post request to OpenAI / whisper-1, and all boils down to not beeing able to connect via https to their server:

1) this works perfectly fine from my laptop, and I get the french text back ;)

curl -v  https://api.openai.com/v1/audio/transcriptions   -H "Authorization: Bearer ----my own api key -------"   -H "Content-Type: multipart/form-data"   -F file="@/home/osboxes/shared/salut.mp3"   -F model="whisper-1"

2) I want to do the same ( via WifiClientSecure ) in the T-Embed

a) I grab the certificate using :

openssl s_client -showcerts -connect api.openai.com:443 </dev/null

b) I put the certif in the following code :

#include <Arduino.h>
#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <ArduinoJson.h>
#include "SD_MMC.h"

void try_connect() {

WiFiClientSecure client;

const char* test_root_ca="-----BEGIN CERTIFICATE-----\n" \
"MIIFKDCCBM6gAwIBAgIQCiYPyyp87Vr6rx8YVcaepDAKBggqhkjOPQQDAjBKMQsw\n" \
"CQYDVQQGEwJVUzEZMBcGA1UEChMQQ2xvdWRmbGFyZSwgSW5jLjEgMB4GA1UEAxMX\n" \
"Q2xvdWRmbGFyZSBJbmMgRUNDIENBLTMwHhcNMjMwMzI4MDAwMDAwWhcNMjQwMzI2\n" \
"MjM1OTU5WjB1MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQG\n" \
"A1UEBxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQQ2xvdWRmbGFyZSwgSW5jLjEe\n" \
"MBwGA1UEAxMVc25pLmNsb3VkZmxhcmVzc2wuY29tMFkwEwYHKoZIzj0CAQYIKoZI\n" \
"zj0DAQcDQgAEZq45AFURHMWZGtVreuNOuVCVO9zy5q79Eco379GbrUKdAQzzdtKG\n" \
"Vp8oIFYFD+32qSpHKcZwalaf16xU0c7rfqOCA2kwggNlMB8GA1UdIwQYMBaAFKXO\n" \
"N+rrsHUOlGeItEX62SQQh5YfMB0GA1UdDgQWBBQeTvJUT72fOjMpDZGuUB5GsnKT\n" \
"rDAwBgNVHREEKTAnghVzbmkuY2xvdWRmbGFyZXNzbC5jb22CDmFwaS5vcGVuYWku\n" \
"Y29tMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH\n" \
"AwIwewYDVR0fBHQwcjA3oDWgM4YxaHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0Ns\n" \
"b3VkZmxhcmVJbmNFQ0NDQS0zLmNybDA3oDWgM4YxaHR0cDovL2NybDQuZGlnaWNl\n" \
"cnQuY29tL0Nsb3VkZmxhcmVJbmNFQ0NDQS0zLmNybDA+BgNVHSAENzA1MDMGBmeB\n" \
"DAECAjApMCcGCCsGAQUFBwIBFhtodHRwOi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMw\n" \
"dgYIKwYBBQUHAQEEajBoMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2Vy\n" \
"dC5jb20wQAYIKwYBBQUHMAKGNGh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9D\n" \
"bG91ZGZsYXJlSW5jRUNDQ0EtMy5jcnQwDAYDVR0TAQH/BAIwADCCAX0GCisGAQQB\n" \
"1nkCBAIEggFtBIIBaQFnAHYA7s3QZNXbGs7FXLedtM0TojKHRny87N7DUUhZRnEf\n" \
"tZsAAAGHKopugAAABAMARzBFAiEAl+s2f5YqdJB9bI2jLHeQ0w2u5UetA9bFnDkW\n" \
"zRKWM9MCIBYdWWHycq0mdyEcM+Xl6AUaDORyXmGlW6QPauYASd9gAHUAc9meiRtM\n" \
"lnigIH1HneayxhzQUV5xGSqMa4AQesF3crUAAAGHKopunQAABAMARjBEAiBQ2u8m\n" \
"vAVxM701nd+7K8BaCzMqcultmJ/Ap9hN5OHm8QIgQU9budkwHeiU+9M4kxliMymj\n" \
"p/lPTv2puWml5kAs4BgAdgBIsONr2qZHNA/lagL6nTDrHFIBy1bdLIHZu7+rOdiE\n" \
"cwAAAYcqim5jAAAEAwBHMEUCIE5EkJBZLdoAzFr7Mgau7UN7LgZ8EFCUML7bkF6e\n" \
"cy9jAiEAo57JtgRCnK0uxI7k1ZseNLOY4/sCyyf7khuxLlmLHIIwCgYIKoZIzj0E\n" \
"AwIDSAAwRQIhANrO5p0Plmso4Q69bixTSJjLVOJXl10Di4Qqi+HE10nzAiA14sPK\n" \
"ZhENjrwuxzRYPhFNkZQQryMJbC/5pUdYcO01Og==\n" \
"-----END CERTIFICATE-----\n" ;

const char* host = "api.openai.com";
const int httpsPort = 443;

if (!client.connect(host, httpsPort)) {
  Serial.println("Connection failed");
  return;
  }
}

and I always get :

[  6232][E][WiFiClientSecure.cpp:144] connect(): start_ssl_client: -1
Connection failed

needless to say there's is no point going any further building the POST headers and sending the "Content-Type: multipart/form-data" stuff and the wav file bytes ;)

Would be great if you could sort me out !!
Thanks,
Jean-Paul

**Comment by lewisxhe** [comment]
start_ssl_client: -1
This kind of problem is generally caused by the failure of certificate verification. This is not a hardware problem

You can try to run this validation
https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiClientSecure/examples/WiFiClientSecure/WiFiClientSecure.ino

**Comment by lewisxhe** [comment]
I noticed that your certificate string does not have a continuation character, the correct one should look like this
```
const char* test_root_ca="-----BEGIN CERTIFICATE-----\n" \
"MIIFKDCCBM6gAwIBAgIQCiYPyyp87Vr6rx8YVcaepDAKBggqhkjOPQQDAjBKMQsw\n" \
"CQYDVQQGEwJVUzEZMBcGA1UEChMQQ2xvdWRmbGFyZSwgSW5jLjEgMB4GA1UEAxMX\n" \
"Q2xvdWRmbGFyZSBJbmMgRUNDIENBLTMwHhcNMjMwMzI4MDAwMDAwWhcNMjQwMzI2\n" \
"MjM1OTU5WjB1MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQG\n" \
"A1UEBxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQQ2xvdWRmbGFyZSwgSW5jLjEe\n" \
"MBwGA1UEAxMVc25pLmNsb3VkZmxhcmVzc2wuY29tMFkwEwYHKoZIzj0CAQYIKoZI\n" \
"zj0DAQcDQgAEZq45AFURHMWZGtVreuNOuVCVO9zy5q79Eco379GbrUKdAQzzdtKG\n" \
"Vp8oIFYFD+32qSpHKcZwalaf16xU0c7rfqOCA2kwggNlMB8GA1UdIwQYMBaAFKXO\n" \
"N+rrsHUOlGeItEX62SQQh5YfMB0GA1UdDgQWBBQeTvJUT72fOjMpDZGuUB5GsnKT\n" \
"rDAwBgNVHREEKTAnghVzbmkuY2xvdWRmbGFyZXNzbC5jb22CDmFwaS5vcGVuYWku\n" \
"Y29tMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH\n" \
"AwIwewYDVR0fBHQwcjA3oDWgM4YxaHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0Ns\n" \
"b3VkZmxhcmVJbmNFQ0NDQS0zLmNybDA3oDWgM4YxaHR0cDovL2NybDQuZGlnaWNl\n" \
"cnQuY29tL0Nsb3VkZmxhcmVJbmNFQ0NDQS0zLmNybDA+BgNVHSAENzA1MDMGBmeB\n" \
"DAECAjApMCcGCCsGAQUFBwIBFhtodHRwOi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMw\n" \
"dgYIKwYBBQUHAQEEajBoMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2Vy\n" \
"dC5jb20wQAYIKwYBBQUHMAKGNGh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9D\n" \
"bG91ZGZsYXJlSW5jRUNDQ0EtMy5jcnQwDAYDVR0TAQH/BAIwADCCAX0GCisGAQQB\n" \
"1nkCBAIEggFtBIIBaQFnAHYA7s3QZNXbGs7FXLedtM0TojKHRny87N7DUUhZRnEf\n" \
"tZsAAAGHKopugAAABAMARzBFAiEAl+s2f5YqdJB9bI2jLHeQ0w2u5UetA9bFnDkW\n" \
"zRKWM9MCIBYdWWHycq0mdyEcM+Xl6AUaDORyXmGlW6QPauYASd9gAHUAc9meiRtM\n" \
"lnigIH1HneayxhzQUV5xGSqMa4AQesF3crUAAAGHKopunQAABAMARjBEAiBQ2u8m\n" \
"vAVxM701nd+7K8BaCzMqcultmJ/Ap9hN5OHm8QIgQU9budkwHeiU+9M4kxliMymj\n" \
"p/lPTv2puWml5kAs4BgAdgBIsONr2qZHNA/lagL6nTDrHFIBy1bdLIHZu7+rOdiE\n" \
"cwAAAYcqim5jAAAEAwBHMEUCIE5EkJBZLdoAzFr7Mgau7UN7LgZ8EFCUML7bkF6e\n" \
"cy9jAiEAo57JtgRCnK0uxI7k1ZseNLOY4/sCyyf7khuxLlmLHIIwCgYIKoZIzj0E\n" \
"AwIDSAAwRQIhANrO5p0Plmso4Q69bixTSJjLVOJXl10Di4Qqi+HE10nzAiA14sPK\n" \
"ZhENjrwuxzRYPhFNkZQQryMJbC/5pUdYcO01Og==\n" \
"-----END CERTIFICATE-----\n" ;

```

**Comment by jalmince** [comment]
PS: the board is of course already connected to my wifi before this runs ;)  ( fails should I say ! )

**Comment by jalmince** [comment]
Hi Lewis !
Many thanks for your dedication and help.
After long googling hours I have found the solution:
that is we have to set:  client.setInsecure() before the connect client attempt ...
That's counter intuitive by the name since we are trying a "secure" connection.... and happened after 3.0 version..
Many thanks again
Jean-Paul
