### ISSUE TITLE
Is it possible to externally charge battery while connected?

### ISSUE THREAD

**Issue by akudan** [Xinyuan-LilyGO/T-Embed#25]
I would like to use the same 3.7V Li-ion battery to power the T-Embed and another microcontroller with its own charging circuit. I want to make sure that when charging the battery from the second microcontroller I will not damage the T-Embed. I imagine this will work okay since typically the charging voltage should be around the max battery voltage (4.2V) but I cannot find any information on the charging IC mentioned in the schematics (TP4065B). Can you confirm that this is possible?

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/T-Embed/assets/22990954/a13bff1c-6e59-4c7f-b6a4-b2e94288550b)
http://www.szyucan.com/upfile/IC-PDF/TP4065.pdf
I don't understand your connection method, this is the manual, unfortunately only in Chinese.
