### ISSUE TITLE
Has anyone had trouble compiling factory.ino ?

### ISSUE THREAD

**Issue by pganson** [Xinyuan-LilyGO/T-Embed#31]
I'm struggling to get this sketch to compile successfully:

- C:\P\data\programming\Arduino\T-Embed-factory/app_controller.cpp:224: undefined reference to `lv_event_get_msg'
- C:\P\data\programming\Arduino\T-Embed-factory/T-Embed-factory.ino:647: undefined reference to `lv_msg_send'

**Comment by lewisxhe** [comment]
lv_msg_send is enabled in [lv_conf.h](https://github.com/Xinyuan-LilyGO/T-Embed/blob/50faf3ed2911faf423489a9e3045e45eb219f808/lib/lvgl/lv_conf.h#L692)



Have you changed the version of lvgl?

**Comment by pganson** [comment]
This was my error.  You can close this issue.
