### ISSUE TITLE
Readme for Arduino Quick Start Doesn't Work for Newer IDE

### ISSUE THREAD

**Issue by mrmonteith** [Xinyuan-LilyGO/T-Embed#38]
On the T-Embed - Readme under Quick Start - Arduino the instructions do not work on the new versions of the IDE.  
[T-Embed](https://github.com/Xinyuan-LilyGO/T-Embed)
 It seems to go through the steps to install.  The search fails
Search for ESP32 in Tools->Board Manager and install ESP32-Arduino SDK 

 Is this the one that is needed now?
![Arduino IDE Screenshot](https://github.com/user-attachments/assets/f834e53b-4215-4c1f-b8d8-5e76bf5b54af)

**Comment by LilyGO** [comment]
Yeah, that's it.

**Comment by mrmonteith** [comment]
Thanks.  I supposed the next line "Copy all files in the lib folder to \Arduino\libraries" doesn't apply?  Seeing there is no lib folder.  Needs to explain where lib is.  Thanks
